# Generated by Django 5.2 on 2025-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("instructor", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("duration", models.IntegerField()),
                ("level", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("rating", models.IntegerField(default=0)),
                ("enrollment_count", models.IntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=255, unique=True
                    ),
                ),
            ],
        ),
    ]
